### ISSUE TITLE
🐛 Bug Report: Unable to log in with self signed certificate

### ISSUE THREAD

**Issue by Ricolo53** [appwrite/sdk-for-cli#141]
### 👟 Reproduction steps

Since the update, it's impossible to login

```
❯ appwrite client --self-signed true
✓ Success: Setting client
❯ appwrite client --debug
endpoint :
key :
cookie :
selfSigned : false
project

✓ Success: Setting client
❯ appwrite client --endpoint "https://my.url/v1" --verbose
Error: Invalid endpoint or your Appwrite server is not running as expected.
    at /snapshot/sdk-for-cli/lib/commands/generic.js:271:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I've done a reset, deleted the configuration json, but nothing works, I can't switch the cli to self-signed.

### 👍 Expected behavior

Business as usual

### 👎 Actual Behavior

Can't use it

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by PromILLEPapst123** [comment]
I'am having the same problem. I can't deploy functions getting this error:

AppwriteException [Error]: fetch failed
    at Client.call (/snapshot/sdk-for-cli/lib/client.js:192:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async accountGet (/snapshot/sdk-for-cli/lib/commands/account.js:60:16) {
  code: undefined,
  response: undefined
}

**Comment by PromILLEPapst123** [comment]
@Ricolo53 how have you done that? I can't redeploy an old backup because it's too far away. Can i downgrade to an old cli? In the internet i could'nt found something this way. Thanks for your respond

**Comment by ChiragAgg5k** [comment]
Hi there !@PromILLEPapst123, it seems to work for me
<img width="348" alt="Image" src="https://github.com/user-attachments/assets/046e88c6-0a32-4f2d-b696-2df2c5eadcb8" />

please feel free to reopen if you again face the issue
