### ISSUE TITLE
🐛 Bug Report: "TypeError: graphql.command is not a function"

### ISSUE THREAD

**Issue by juzo** [appwrite/sdk-for-cli#71]
### 👟 Reproduction steps

After installation on MacOS I type the following
```
appwrite -v
```
and get this error report:
```
/opt/homebrew/Cellar/appwrite/HEAD-9007d34/libexec/lib/node_modules/appwrite-cli/lib/commands/graphql.js:67
    .command(`query`)
     ^

TypeError: graphql.command is not a function
    at Object.<anonymous> (/opt/homebrew/Cellar/appwrite/HEAD-9007d34/libexec/lib/node_modules/appwrite-cli/lib/commands/graphql.js:67:6)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/appwrite/HEAD-9007d34/libexec/lib/node_modules/appwrite-cli/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)

Node.js v19.5.0
```

I tried installing it using all the methods provided: NPM, Homebrew and terminal. Outcome is the same.

### 👍 Expected behavior

It should show the version number.

### 👎 Actual Behavior

```
/opt/homebrew/Cellar/appwrite/HEAD-9007d34/libexec/lib/node_modules/appwrite-cli/lib/commands/graphql.js:67
    .command(`query`)
     ^

TypeError: graphql.command is not a function
    at Object.<anonymous> (/opt/homebrew/Cellar/appwrite/HEAD-9007d34/libexec/lib/node_modules/appwrite-cli/lib/commands/graphql.js:67:6)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/appwrite/HEAD-9007d34/libexec/lib/node_modules/appwrite-cli/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)

Node.js v19.5.0
```

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@juzo thanks for creating this issue! 🙏🏼 We'll look into this right away.

As a workaround, I would suggest uninstalling it from homebrew and installing it via NPM.

> I tried installing it using all the methods provided: NPM, Homebrew and terminal. Outcome is the same.

Make sure the homebrew version is not being used when you're testing with other installation methods.

**Comment by juzo** [comment]
Thanks for the reply. I uninstalled everything and tried installing it again but only using the terminal version (curl). This time it worked.

```
appwrite -v
1.1.1
```
