### ISSUE TITLE
🚀 Feature: Improve Error Message when Authentication is Reuqired

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-cli#80]
### 🔖 Feature description

If the cookie in the pref.json is set but invalid, `appwrite init project` returns with:

```
✗ Error User (role: guests) missing scope (projects.read)
```

<details>
<summary>with verbose</summary>

```shell
$ appwrite init project --verbose
? How would you like to start? Link this directory to an existing Appwrite project
AppwriteException [Error]: User (role: guests) missing scope (projects.read)
    at Client.call (/Users/steven/.nvm/versions/node/v16.16.0/lib/node_modules/appwrite-cli/lib/client.js:209:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async projectsList (/Users/steven/.nvm/versions/node/v16.16.0/lib/node_modules/appwrite-cli/lib/commands/projects.js:33:16)
    at async Object.choices (/Users/steven/.nvm/versions/node/v16.16.0/lib/node_modules/appwrite-cli/lib/questions.js:129:28) {
  code: 401,
  response: [Object: null prototype] {
    message: 'User (role: guests) missing scope (projects.read)',
    code: 401,
    type: 'general_unauthorized_scope',
    version: 'dev',
    file: '/usr/src/code/app/controllers/general.php',
    line: 365,
    trace: [
      [Object: null prototype],
      [Object: null prototype],
      [Object: null prototype]
    ]
  }
}
✗ Error User (role: guests) missing scope (projects.read)
```
</details>

It would be nice if the error message was more helpful. Tanmoy Karmakar has suggested:

> Cannot access projects. Login is required use `appwrite login` command

FYI, if the cookie is not set we respond with:

```
✗ Error Session not found. Please run `appwrite login` to create a session
```

### 🎤 Pitch

The current error is very technical and doesn't give the user any guidance on how to proceed. A clearer, more helpful error message will create a better developer experience.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Udassi-Pawan** [comment]
I would like to work on this issue, would you assign it to me?

**Comment by stnguyen90** [comment]
@Udassi-Pawan assigned! Thanks for your interest! 🙏🏼 Remember to make the change in our [sdk-generator repo](https://github.com/appwrite/sdk-generator/tree/master/templates/cli)!

**Comment by ChiragAgg5k** [comment]
Due to stale progress, this issue is now re open for other contributions

**Comment by yadavshubham01** [comment]
Hi @ChiragAgg5k,
Is this issue still open? If so, could you please assign it to me? I'd love to work on it.

**Comment by ChiragAgg5k** [comment]
@yadavshubham01 feel free to raise a PR, no need to be assigned. ping me for review
