### ISSUE TITLE
🐛 Bug Report: Manual install doesn't work

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-cli#95]
### 👟 Reproduction steps

1. Manually install the CLI
2. Run `appwrite -v`

One line script to test in a container:

```shell
docker run --rm -it ubuntu sh -c "apt update && apt install -y curl && curl -sL https://appwrite.io/cli/install.sh | bash && appwrite -v"
```

### 👍 Expected behavior

it works

### 👎 Actual Behavior

Error:

```
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: Cannot find module '/snapshot/sdk-for-cli/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/sdk-for-cli/node_modules/axios/package.json',
  pkg: true
}
```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite CLI version 4.0.0.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shiba-Kar** [comment]
`` > curl -sL https://appwrite.io/cli/install.sh | bash``
`> appwrite`

same above error !!
``brew tap appwrite/sdk-for-cli https://github.com/appwrite/sdk-for-cli 
brew update
brew install --HEAD appwrite``

works !!

**Comment by JimWuerch** [comment]
Any workarounds for getting this working on linux?

**Comment by baskrahmer** [comment]
@JimWuerch you can install from source by changing the link:

```$ curl -sL https://raw.githubusercontent.com/appwrite/sdk-for-cli/master/install.sh | bash```

Probably best to select a version from a release though as opposed to the master branch.

**Comment by Weav3r** [comment]
@JimWuerch curl the install file from this repo. checkout issue #100

**Comment by christianmqm** [comment]
@Weav3r You mean this npm package?

```
:~# npm install -g appwrite-cli

changed 77 packages, and audited 78 packages in 6s

16 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
:~# appwrite -v
/usr/local/lib/node_modules/appwrite-cli/lib/parser.js:26
            if (data[key]?.constructor?.name === 'BigNumber') {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appwrite-cli/index.js:11:44)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
